from pathlib import Path
import re
import shutil
import hashlib

ROOT = Path(__file__).resolve().parent.parent
PLAN = ROOT / 'work' / 'planning'
BACKUP = ROOT / 'work' / 'archive' / 'before-character-renaming-v1'
assert not BACKUP.exists(), 'Naming migration already started; inspect state instead of rerunning.'
BACKUP.mkdir(parents=True)
shutil.copytree(PLAN, BACKUP / 'planning')
chapter = ROOT / 'work' / 'manuscript' / '01-the-kings-measure.md'
shutil.copy2(chapter, BACKUP / chapter.name)
builder = ROOT / 'work' / 'build_planning_package.py'
shutil.copy2(builder, BACKUP / builder.name)
shutil.copy2(ROOT / 'outputs' / 'schlelberg-planning-package.zip', BACKUP / 'schlelberg-planning-package-v1.zip')

names = {
    'Toby': 'Tobious', 'Ipin': 'Ypin', 'Panji': 'Panjios',
    'Maria': 'Mariya', 'Sus': 'Suss', 'Eda': 'Edda',
    'Saman': 'Samon', 'Lio': 'Lios', 'Daran': 'Darran',
    'Theren': 'Therren', 'Neris': 'Nerissa', 'Oran': 'Orran',
    'Thesa': 'Thesia', 'Pell': 'Pehl', 'Anet': 'Annet',
    'Hessa': 'Hessah', 'Jora': 'Jorra', 'Senn': 'Sennos',
}
pattern = re.compile(r'\b(' + '|'.join(map(re.escape, names)) + r')\b')
def rename(text):
    return pattern.sub(lambda m: names[m[0]], text)

source_files = [Path('C:/Users/Rafif/Downloads/Schlelberg - Draft 3 (1).docx'),
                Path('C:/Users/Rafif/.codex/attachments/09ea2bf3-73a2-4578-8bd7-20567a845ea9/Pasted text.txt')]
source_hashes = {p: hashlib.sha256(p.read_bytes()).hexdigest() for p in source_files}

for path in PLAN.glob('*.md'):
    if path.name == 'validation.md':
        continue  # Regenerated by the package builder.
    text = path.read_text(encoding='utf-8')
    if path.name == '11-editorial-audit.md':
        lines = []
        for line in text.splitlines(keepends=True):
            # Original-source diagnosis stays truthful to the original manuscript;
            # only the reconstruction column uses the new names.
            if line.startswith(('| Critical ', '| Major ', '| Moderate ')):
                cells = line.split('|')
                cells[-2] = rename(cells[-2])
                lines.append('|'.join(cells))
            else:
                lines.append(rename(line))
        text = ''.join(lines)
        text = text.replace("The 'Tobious Leader' concept", "The original 'Toby Leader' concept")
        text = text.replace('The spoken sequence currently ends:', 'The spoken sequence in the renamed English draft currently ends:')
        text = text.replace('The source map in `reference/original-manuscript-map.md` records paragraph spans and clearly separates source facts from earlier proposals.',
            'The source map in `reference/original-manuscript-map.md` records paragraph spans and clearly separates source facts from earlier proposals. The source-description column below retains original character names; the reconstruction column uses the author-selected new names. See `naming-canon.md` for the exact mapping.')
    else:
        text = rename(text)
    text = text.replace('original plural-Tobious idea', 'original plural-Toby idea')
    text = text.replace('species called Tobious.', "species called 'Toby' in the original.")
    text = text.replace('“Tobious. Listen.', '“Tobi. Listen.')
    text = re.sub(r'\bversion 1\b(?!\.)', 'version 1.1', text)
    if path.name == '00-START-HERE.md':
        text = text.replace('## Read order', '## Confirmed character names\n\nAll 18 character names were selected by the author in six interactive batches after the initial plan. See `naming-canon.md` for the full mapping, intended pronunciations, and formal-name/nickname rules. Use these names in all new prose; original source documents intentionally retain their historical spellings. This revision changes names, not events or character identities.\n\n## Read order')
    if path.name == 'handover.md':
        text = text.replace("The latest 'lanjut' continues the planning work.", 'The complete plan was delivered, then the author selected new names for all 18 characters through six interactive batches. This version incorporates those choices without resuming prose drafting.')
        text = text.replace('All other new names, ages, dates, mechanics, and chapter choices are **design-locked planner decisions**', 'The character names in `naming-canon.md` are also explicitly author-selected. Other place/institution names, ages, dates, mechanics, and chapter choices are **design-locked planner decisions**')
        text = text.replace('| `validation.md` |', '| `naming-canon.md` | All 18 confirmed renames, pronunciations, and familiar-name rules |\n| `validation.md` |')
        text = text.replace('Keep the draft unmodified during this planning-only phase; apply the patch before writing Chapter 2.', 'The draft has received the authorized character renames only. Its separate plot-continuity patch remains pending; apply that patch before writing Chapter 2.')
        text = text.replace('## Next concrete actions', '## Latest completed change: names\n\nAll 18 renames were explicitly selected by the author, propagated through the active modules and existing English Chapter 1, and included in the regenerated master and ZIP. Tobious/Tobi, Panjios/Panji, and Lios/Lio are full-name/familiar-name pairs. Ypin is intended to be pronounced i-pin. The source DOCX, source map, original request, and archived historical snapshots keep their original spellings. This is naming revision 1.1; plot and outcomes have not changed.\n\n## Next concrete actions')
    if path.name == '03-character-bible.md':
        text = text.replace('## Tobious — 23 at Chapter 1', 'Naming revision 1.1: use full names in narration, chapter cards, records, and official address. Familiar names are Tobi (Tobious), Panji (Panjios), and Lio (Lios); introduce each connection naturally. See `naming-canon.md` for all 18 confirmed names and pronunciation guides.\n\n## Tobious — 23 at Chapter 1')
    if path.name == '10-execution-protocol.md':
        text = text.replace('## Style and tone', '## Name usage\n\nThe author confirmed all 18 names in `naming-canon.md`. Full forms in narration: Tobious, Panjios, Lios. Familiar forms in appropriate dialogue: Tobi, Panji, Lio. The opening echo uses “Tobi. Listen.” and Chapter 31 must repeat that exactly. Ypin is pronounced i-pin. Do not silently revert to original source spellings or give everyone a new nickname. The source documents retain original names intentionally.\n\n## Style and tone')
    if path.name == 'README-ID.md':
        text = text.replace('## Arah ceritanya', '## Pembaruan nama — versi 1.1\n\nSeluruh 18 pilihan nama dari enam putaran interaktif sudah diterapkan. Daftar lengkap dan pelafalannya ada di **naming-canon.md**. Tobious dipanggil Tobi, Panjios dipanggil Panji, dan Lios dipanggil Lio. Alur, peran, dan nasib tokoh tidak berubah. Naskah sumber asli tetap memakai nama lamanya untuk keperluan rujukan.\n\n## Arah ceritanya')
    path.write_text(text, encoding='utf-8')

old_prose = chapter.read_text(encoding='utf-8')
new_prose = rename(old_prose)
new_prose = new_prose.replace('“I saw it, Tobious.”', '“I saw it, Tobi.”')
new_prose = new_prose.replace('“Tobious. Listen.', '“Tobi. Listen.')
chapter.write_text(new_prose, encoding='utf-8')
assert 'They came here for you.' in new_prose
assert 'That door is what they came for.' not in new_prose
assert '“Tobious. He repairs the water gates every season.”' in new_prose
assert '“Tobi. Listen. They aren\'t looking for stores.”' in new_prose

pronunciations = ['to-bi-us', 'i-pin', 'pan-ji-os', 'ma-ri-ya', 'sus', 'e-da', 'sa-mon', 'li-os', 'da-ran', 'te-ren', 'ne-ris-sa', 'o-ran', 'te-si-a', 'pel', 'a-net', 'he-sa', 'jo-ra', 'sen-nos']
familiar = {'Toby': 'Tobi (to-bi)', 'Panji': 'Panji (pan-ji)', 'Lio': 'Lio (li-o)'}
canon = '''# CONFIRMED CHARACTER NAMES — REVISION 1.1

The author selected every entry below through six interactive batches. These are author-locked spellings, not tentative suggestions. All characters retain the same identity, role, age, relationships, and outcome. Pronunciations are intended readings, expressed for the Indonesian-speaking author; they do not guarantee every English reader's first interpretation or constitute a formal phonetic transcription.

| Original/reference name | Current full name | Intended pronunciation | Familiar name |
|---|---|---|---|
'''
for (old, new), sound in zip(names.items(), pronunciations):
    canon += f'| {old} | **{new}** | {sound} | {familiar.get(old, "Same as full name")} |\n'
canon += '''
## Use in prose

Use Tobious, Panjios, and Lios as the stable narration/record forms. Tobi, Panji, and Lio are familiar names in dialogue when the relationship permits them. Establish each full-name/familiar-name connection naturally at introduction; do not insert a pronunciation lecture into the scene. Mariya may call Tobious Tobi privately; she gives his full name when identifying him to an official. Panjios can invite his trainees to call him Panji. Lios can identify himself and add that people call him Lio. Avoid turning every switch into a symbolic event or implying that a short name is a separate person.

The opening's future self addresses his younger self as **“Tobi. Listen. They aren't looking for stores.”** Chapter 31 must repeat the exact same form. This naming update does not apply the separate pending change to the opening's final warning.

**Ypin is i-pin**, not ai-pin. A single unobtrusive cast/pronunciation guide in a future edition is possible if needed; no change of spelling is authorized merely because a reader might initially pronounce it differently. Thesia, Nerissa, Sennos, Samon, and the longer formal names intentionally differ somewhat from the old pronunciations because the author selected those options.

All other names in the table have no newly invented nickname. Use Suss, never the old Sus spelling in current-story prose. Use Mariya, never Maria in current-story prose. The Iwang / the Hollow Ones remains unchanged: it is a species label, not part of this character rename. Locations, organizations, sword names, chronology, and the book title remain unchanged.

## Authority and preserved sources

The original DOCX, original editorial request, factual original-manuscript map, and archived earlier snapshots retain their original names. Source-analysis passages may quote those names explicitly. Use this mapping to interpret them; never mistake an original spelling for a new cast member. Current chapter cards, rules, relationships, prompts, continuity, and the reconstructed English Chapter 1 use the selected names.

Only naming and its documentation changed in revision 1.1. The 32 chapters, 96 scene cards, POV allocation, captive counts, and permanently separated surviving couple are unchanged. All six naming batches are complete; do not ask the author to choose again.
'''
(PLAN / 'naming-canon.md').write_text(canon, encoding='utf-8')

code = rename(builder.read_text(encoding='utf-8'))
code = re.sub(r'\b([Vv]ersion) 1\b(?!\.)', r'\1 1.1', code)
code = code.replace('Existing English Chapter 1 included as an unchanged working reference;', 'Existing English Chapter 1 includes the 18-character naming revision where applicable;')
code = code.replace("PLAN / 'validation.md']", "PLAN / 'validation.md', PLAN / 'naming-canon.md']")
code = code.replace("assert len(z.namelist()) == 19", "assert len(z.namelist()) == 20")
code = code.replace("'zip_files': 19", "'zip_files': 20")
code = code.replace('chapter counts', 'chapter counts')
# Include the authoritative name table in the human-readable master, while the
# 12 numbered modules retain their existing identities and validation.
code = code.replace("for source in modules:\n    first_heading", "for source in modules + [PLAN / 'naming-canon.md']:\n    first_heading")
code = code.replace("for source in modules:\n    body", "for source in modules + [PLAN / 'naming-canon.md']:\n    body")
code = code.replace('- Wrong original source and obsolete Indonesian draft excluded from this package.', '- All 18 author-selected name changes are documented in naming-canon.md; full-name and familiar-name usage is explicit.\n- Wrong original source and obsolete Indonesian draft excluded from this package.')
code = code.replace("('00-START-HERE.md', 'Author locks versus design locks')", "('naming-canon.md', 'All 18 author-confirmed name selections'), ('00-START-HERE.md', 'Author locks versus design locks')")
code = code.replace('Read [handover](planning/handover.md)', 'All 18 author-selected names are in [naming canon](planning/naming-canon.md), applied to the active plan and Chapter 1. Familiar names: Tobi, Panji, Lio.\n\nRead [handover](planning/handover.md)')
builder.write_text(code, encoding='utf-8')

session = ROOT / 'work' / 'naming-session.md'
session.write_text('''# Character naming session — complete

All six interactive batches were answered by the author. Batch 6 confirmed Hessa → Hessah (he-sa), Jora → Jorra (jo-ra), and Senn → Sennos (sen-nos).

The full 18-entry author-approved mapping is now the canonical [naming guide](planning/naming-canon.md). Active planning modules and the reconstructed English Chapter 1 have been updated. Original source materials and historical snapshots retain their original names. Pre-rename working files and the version-1 delivery ZIP are backed up under work/archive/before-character-renaming-v1/.

The initial question UI disappeared; reissuing the questions and keeping the turn open with an input-interruptible wait worked. All naming choices are settled. No further naming questions are needed unless the author reopens them.

Package regeneration and verification follow this migration. The separate plot-continuity patch to the opening remains pending; only authorized names and familiar address changed here.
''', encoding='utf-8')
for source, before in source_hashes.items():
    assert hashlib.sha256(source.read_bytes()).hexdigest() == before
print('Applied all 18 confirmed names. Original source files unchanged. Ready to rebuild package.')
